### ISSUE TITLE
Auto error tracking only

### ISSUE THREAD

**Issue by nicooprat** [veliovgroup/ostrio-analytics#1]
I'd like to track errors only, as I'm already using some other tracking services like Google Analytics or Intercom.

If I set `auto` to `false` (as described here https://github.com/VeliovGroup/ostrio-analytics#constructor-new-analyticstrackingid--auto), will Ostrio still track errors automatically? If not, how could I get it to work this way?

Thanks.

PS. Working with Meteor.

**Comment by dr-dimitru** [comment]
Hello @nicooprat ,

Yes this is possible, but not fully automatically. Use code below:
```js
import Analytics from 'meteor/ostrio:analytics';
const analyticsTracker = new Analytics('trackingId', false);

const onerror   = window.onerror;
window.onerror = function (msg, url, line, column) {
  analyticsTracker.pushEvent('[Global Error]', 'Error: ' + msg + '. File: ' + url + ' At: ' + line + ':' + column);

  if (onerror) {
    onerror.apply(this, arguments);
  }
};
```

Of if you're using NPM integration:
```js
const analyticsTracker = new (require('ostrio-analytics'))('trackingId', false);

const onerror   = window.onerror;
window.onerror = function (msg, url, line, column) {
  analyticsTracker.pushEvent('[Global Error]', 'Error: ' + msg + '. File: ' + url + ' At: ' + line + ':' + column);

  if (onerror) {
    onerror.apply(this, arguments);
  }
};
```

Let me know if this is working for you.

**Comment by nicooprat** [comment]
Great, thanks, will try :)

**Comment by nicooprat** [comment]
Quick question, does Ostrio also track server-side errors? I guess not with this simple config, but in any other way?

**Comment by dr-dimitru** [comment]
@nicooprat no, no server errors tracking.
Take a look at our [open source logging packages](https://github.com/VeliovGroup?utf8=✓&q=logger&type=&language=) for Meteor

**Comment by dr-dimitru** [comment]
Hello @nicooprat ,

Have you solved it?

**Comment by nicooprat** [comment]
Hi, didn't have time to test, but I guess we can close the issue ;)

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if the issue isn't solved on your end.
